title: Felice's Blog
theme: minima
author: flchan2022
email: felice.lee.chan@intel.com
description: > # this means to ignore newlines until "baseurl:"
  I am editing this line in _config.yml.  Let's see if it will show up in "head meta" (for
  Google search results), and what is my feed.xml site along with its description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
